name: Yarn cache
description: A composite action to cache yarn packages
inputs:
  cache-dir:
    description: A list of files, directories, and wildcard patterns to cache and restore
outputs:
  cache-hit:
    description: A boolea value indicating a cache hit
    value: ${{ steps.cache-yarn.outputs.cache-hit }}
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        echo "------------------------------------------------------------------------------------"
        echo "\n"
        echo "\n"
        echo "\n"
        echo "Input: ${{ inputs.cache-dir }}"
        echo "\n"
        echo "\n"
        echo "\n"
        echo "------------------------------------------------------------------------------------"

    - id: cache-yarn
      uses: actions/cache@v3
      shell: bash
      with:
        path: ${{ inputs.cache-dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
