name: Yarn cache
description: A composite action to cache yarn packages
inputs:
  cache-dir:
    description: A list of files, directories, and wildcard patterns to cache and restore
    required: true
outputs:
  cache-hit:
    description: indicates whether there was a cache hit (true) or miss (false)
    value: ${{ steps.cache-yarn.outputs.cache-hit }}
runs:
  using: composite
  steps:
    - id: cache-yarn
      uses: actions/cache@v3
      shell: bash
      with:
        path: ${{ inputs.cache-dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
