name: Yarn cache
description: A composite action to cache yarn packages
outputs:
  cache-hit:
    description: indicates whether there was a cache hit (true) or miss (false)
    value: ${{ steps.cache-yarn.outputs.cache-hit }}
runs:
  using: composite
  steps:
    - id: yarn-cache-dir-path
      shell: bash
      run: |
        echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

    - id: cache-yarn
      uses: actions/cache@v3
      shell: bash
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
